In [2]:
import torch

embedding = torch.randn(100, 4)
tokens = torch.tensor([
    [4, 5, 6],
    [2, 3, 4],
    [6, 7, 8],
    [8, 9, 10]
])

x = embedding[tokens]
print(x)
print(x.shape)

tensor([[[ 1.4922, -0.1429, -0.4196,  0.4637],
         [ 0.3741, -0.7940,  0.2258, -1.0832],
         [ 0.1343,  0.0240,  0.4671,  0.4108]],

        [[-0.8527, -0.7696,  0.2588, -2.4369],
         [ 0.7406,  0.9033, -1.7893, -0.9662],
         [ 1.4922, -0.1429, -0.4196,  0.4637]],

        [[ 0.1343,  0.0240,  0.4671,  0.4108],
         [-0.6426,  0.2163, -0.6329, -0.0586],
         [-0.8822, -0.6517, -0.2625,  0.7984]],

        [[-0.8822, -0.6517, -0.2625,  0.7984],
         [-0.3207, -0.9657,  0.5957, -0.3305],
         [ 2.7184,  0.2542,  1.6304, -0.4371]]])
torch.Size([4, 3, 4])


In [4]:
print(x[0])
print(x[0].shape)

tensor([[ 1.4922, -0.1429, -0.4196,  0.4637],
        [ 0.3741, -0.7940,  0.2258, -1.0832],
        [ 0.1343,  0.0240,  0.4671,  0.4108]])
torch.Size([3, 4])


In [ ]:
# select first sentence, first token => 4 numbers
print(x[0, 0])
print(x[0, 0].shape)

tensor([ 1.4922, -0.1429, -0.4196,  0.4637])
torch.Size([4])


In [ ]:
# select 1st token from all the sentences
print(x[:, 0, :])
print(x[:, 0, :].shape)


tensor([[ 1.4922, -0.1429, -0.4196,  0.4637],
        [-0.8527, -0.7696,  0.2588, -2.4369],
        [ 0.1343,  0.0240,  0.4671,  0.4108],
        [-0.8822, -0.6517, -0.2625,  0.7984]])
torch.Size([4, 4])


In [10]:
print(x[:, :, 0])
print(x[:, :, 0].shape)

tensor([[ 1.4922,  0.3741,  0.1343],
        [-0.8527,  0.7406,  1.4922],
        [ 0.1343, -0.6426, -0.8822],
        [-0.8822, -0.3207,  2.7184]])
torch.Size([4, 3])


In [11]:
print(x[0, :, :])
print(x[0, :, :].shape)

tensor([[ 1.4922, -0.1429, -0.4196,  0.4637],
        [ 0.3741, -0.7940,  0.2258, -1.0832],
        [ 0.1343,  0.0240,  0.4671,  0.4108]])
torch.Size([3, 4])
