In [1]:
import torch

x = torch.tensor([
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ],
    [
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
])

print(x.shape)

torch.Size([2, 3, 4])


In [ ]:
y = x.reshape(6, 4) # colapses batch and sequence dimensions
print(y)
print(y.shape)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])
torch.Size([6, 4])


In [4]:
y = x.transpose(1, 2)
print(x.shape)
print(y.shape)

print(x[0])
print(y[0])

torch.Size([2, 3, 4])
torch.Size([2, 4, 3])
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
tensor([[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]])
